version: '3.8'

services:

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:

     - './back:/usr/src'
     - /var/run/docker.sock:/var/run/docker.sock
     - ./docker-compose-files:/docker-compose-files
    ports:
     - "8000:8000"
    tty: true
    stdin_open: true
    privileged: true



  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
     - './front/mysite:/usr/src'
    ports:
     - "8080:8080"
    tty: true
    stdin_open: true
    depends_on:
     - back
    environment:
     - NODE_ENV=development

  