# Generated by Django 4.2 on 2023-07-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='学年')),
                ('student_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='学籍番号')),
                ('classification', models.CharField(max_length=10, null=True, verbose_name='学校区分')),
                ('department', models.CharField(blank=True, max_length=30, null=True, verbose_name='学科')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='学校名')),
                ('graduation_year', models.CharField(max_length=5, null=True, verbose_name='卒業年度')),
            ],
        ),
    ]
