# Generated by Django 4.2 on 2023-07-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='student_number',
        ),
    ]
