# Generated by Django 4.2 on 2023-07-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_school_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='faculty',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='学部'),
        ),
    ]
