# Generated by Django 4.2 on 2023-09-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='classification',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='学校区分'),
        ),
        migrations.AlterField(
            model_name='school',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='卒業年度'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='学校名'),
        ),
    ]
