# Generated by Django 4.2 on 2024-01-11 01:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge_group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('introduction', models.CharField(blank=True, max_length=1000, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('finish', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('admins', models.ManyToManyField(blank=True, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(blank=True, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'judge_group',
            },
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('problem', models.TextField(null=True, verbose_name='問題')),
                ('difficulty', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('target_time', models.IntegerField(default=5, null=True, verbose_name='目標回答時間')),
                ('sample_explanation', models.TextField(null=True, verbose_name='サンプル説明')),
                ('is_public', models.BooleanField(default=True)),
                ('group_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
            ],
            options={
                'db_table': 'problems',
            },
        ),
        migrations.CreateModel(
            name='Submission_results',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=20)),
                ('code', models.TextField(null=True)),
                ('status', models.CharField(blank=True, default='NG', max_length=10)),
                ('score', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('group_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='judge.judge_group')),
                ('problem_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='judge.problems')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submission_results',
            },
        ),
        migrations.CreateModel(
            name='Sample_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.TextField(null=True)),
                ('answer', models.TextField(null=True)),
                ('problem_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='judge.problems')),
            ],
            options={
                'db_table': 'sample_case',
            },
        ),
        migrations.AddField(
            model_name='judge_group',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='judge_groups', to='judge.problems', verbose_name='問題'),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.TextField(null=True)),
                ('answer', models.TextField(null=True)),
                ('problem_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='judge.problems')),
            ],
            options={
                'db_table': 'test_case',
            },
        ),
    ]
