# Generated by Django 4.2 on 2024-01-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scout',
            field=models.BooleanField(default=False),
        ),
    ]
