# Generated by Django 4.2 on 2024-01-12 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_scout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='scout',
            new_name='scout_receive',
        ),
    ]
